import Head from "next/head";
import Layout from "./layouts/Layout";
import Main from "./layouts/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>메디밸류</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
