import Head from "next/head";
import MainLayout from "../layouts/main";
import { MainIndex } from "./main";

// ----------------------------------------------------------------------
Home.getLayout = (page) => <MainLayout> {page} </MainLayout>;
// ----------------------------------------------------------------------

export default function Home() {
  return (
    <>
      <Head>
        <title>메디밸류</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainIndex />
    </>
  );
}
